# Generated by Django 4.1.5 on 2023-02-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModilim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=21)),
            ],
        ),
        migrations.AlterModelOptions(
            name='mymodel',
            options={'ordering': ['id'], 'verbose_name_plural': 'Mening Modelim'},
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
