# Generated by Django 4.1.5 on 2023-02-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_mymodilim_alter_mymodel_options_alter_mymodel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dostavka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('count', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('price', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('yetkazib berilgan', 'Yetkazib berilgan'), ('tayyorlanyabdi', 'Tayyorlanyabdi')], default='tayorlanyabdi', max_length=255)),
            ],
            options={
                'verbose_name': 'Dastavka',
                'verbose_name_plural': 'Das',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='MyModilim',
        ),
    ]
